AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template
Resources:
    Ec2Instance:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: ami-467ca739 # Amazon Linux AMI in N.Virginia
        Tags:
          - Key: Name
            Value: A simple example
        InstanceType: t2.micro
        SecurityGroups: 
            - !Ref 'FIRSTSecurityGroup'      
    FIRSTSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
        GroupDescription: Enable SSH access via port 22
        SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
            FromPort: 22
            IpProtocol: tcp
            ToPort: 22